export const State = {
  FAILED: 'FAILED',
  IN_PROGRESS: 'IN_PROGRESS',
  SUCCESS: 'SUCCESS',
};

export default {
  SET_DIET: "SET_DIET",
  SET_THEME: "SET_THEME",
  SET_RECIPE: "SET_RECIPE",
  SET_RECIPES: "SET_RECIPES",
  SET_FAVORITES: "SET_FAVORITES",
  UPDATE_CART: "UPDATE_CART",
}